### PR TITLE
Added support for device orientation change

### PR DESCRIPTION
**Pull request by chemitaxis**
This PR add device orientation change on devices (tablets and mobiles)

### CODE REVIEW

**Comment by chemitaxis** [comment]
Hi, I have tested and added listener event for device orientation change. Thanks!

**Comment by chemitaxis** [comment]
Hi, can you check this? Thanks.

**Comment by chemitaxis** [comment]
Hi! Any news here? Thanks!

**Comment by soulwire** [comment]
Thanks and sorry for the long wait!

**Pull request merged**
