### PR TITLE
Export the module in order to use it with browserify or webpack

### PR DESCRIPTION
**Pull request by lbineau**

### CODE REVIEW

**Comment by soulwire** [comment]
Thanks for the PR :)

Could you make sure it'll [still work in the browser](http://www.richardrodger.com/2013/09/27/how-to-make-simple-node-js-modules-work-in-the-browser/#.VufpkpOLRQI) though, by checking if `module` and `module.exports` exist? Something like:

```
if( typeof exports !== 'undefined' ) {
  if( typeof module !== 'undefined' && module.exports ) {
    exports = module.exports = fit;
  }
  exports.fit = fit;
} 
```

**Comment by lbineau** [comment]
Ok I did. Do you use an app to minify the JS ? 
Thanks for this helpful library, especially the math part, I use it with pixi and it works like a charm !
I've been looking for it for years now :)

**Comment by soulwire** [comment]
Great, thank you!

**Comment by lbineau** [comment]
I also had to publish your [library to npm](https://registry.npmjs.org/fit.js) with my npm account (https://docs.npmjs.com/getting-started/publishing-npm-packages).
So I'm the npm user, but you are still the author of the library if it is ok for you!

**Comment by soulwire** [comment]
Sure, thanks for doing that :)

**Pull request merged**
